# NumPy

NumPy es una biblioteca de Python utilizada para trabajar con matrices.

También tiene funciones para trabajar en el dominio del álgebra lineal, la transformada de Fourier y las matrices.

NumPy fue creado en 2005 por Travis Oliphant. Es un proyecto de código abierto y se puede utilizar libremente.

NumPy significa Numerical Python.

En Python tenemos las listas que cumplen la función de los arrays, pero son lentas.

NumPy pretende proporcionar un objeto array que sea hasta 50 veces más rápido que las listas tradicionales de Python.

El objeto array en NumPy se llama ndarray, y proporciona un montón de funciones de apoyo que hacen que trabajar con ndarray sea muy fácil.

Los arrays se utilizan con mucha frecuencia en la ciencia de datos, donde la velocidad y el consumo de los recursos son muy importantes.

NumPy es una biblioteca de Python y está escrita parcialmente en Python, pero la mayoría de las partes que requieren un cálculo rápido están escritas en C o C++.

Para usar numpy necesitamos instalarlo primero (si estamos usando Anaconda vendrá ya pre-instalado): *pip install numpy*

Una vez instalado podemos empezar a usarlo:






In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Podemos crear matrices de la misma manera:

In [4]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Segundo elemento de la primera fila: ', arr[0, 1]) 

Segundo elemento de la primera fila:  2


De hecho, podemos incluso crear arrays tridimensionales:

In [5]:
arr = np.array([
                [[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]
               ])

print(arr[0, 1, 2]) 

6


Por supuesto, podemos usar indexación negativa como en cualquier lista estándar:

In [8]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Último elemento de la segunda dimensión: ', arr[1, -1]) 

Último elemento de la segunda dimensión:  10


## Funciones incorporadas para generación arrays/vectores y matrices

Numpy incorporta métodos para generar un arrays rellenos de ceros o unos:

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

Hay muchas situaciones en las que tienes un rango de números y te gustaría dividir por igual ese rango de números en intervalos. El método linspace de NumPy está diseñado para resolver este problema. linspace tiene tres argumentos:
- El inicio del intervalo
- El fin del intervalo
- El número de subintervalos en los que deseas que se divida el intervalo

Un ejemplo del método linspace es el siguiente:

In [12]:
np.linspace(0, 1, 10)

#Devuelve array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Vualquiera que haya estudiado álgebra lineal estará familiarizado con el concepto de un "matriz identidad", que es una matriz  cuadrada cuyos valores diagonales son todos 1. NumPy tiene una función incorporada que incluye un argumento para construir matrices identidad. La función es eye:

In [14]:
print(np.eye(1))

#Devuelve un arreglo identidad de 1x1

print(np.eye(2) )

#Devuelve un arreglo identidad de 2x2

print(np.eye(50))

#Devuelve un arreglo identidad de 50x50

[[1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


## Números aleatorios en NumPy

NumPy incorpora algunas funciones para generar números aleatorios:

In [16]:
np.random.rand(7)
#Devuelve una muestra de números aleatorios entre 0 y 1.



array([0.33034017, 0.11262874, 0.86918057, 0.129774  , 0.61013947,
       0.05218418, 0.59974363])

In [18]:
np.random.rand(4,4)
#El tamaño de la muestra puede ser un número entero (para un arreglo unidimensional) o dos enteros separados por comas (para un arreglo bidimensional).

array([[0.01531609, 0.91438269, 0.89400109, 0.7428334 ],
       [0.97666053, 0.14864733, 0.25036153, 0.70479718],
       [0.99758777, 0.89453816, 0.19853942, 0.76772751],
       [0.43782581, 0.67697485, 0.23805486, 0.90439523]])

In [20]:
np.random.randn(20)

#Devuelve una muestra de números aleatorios entre siguiendo la distribución normal 1,1.

array([-0.16029577, -0.67872737,  1.63835313,  0.6193012 ,  0.86681734,
        0.42966533,  0.71084017, -0.39857576, -0.61439971,  1.5293525 ,
       -0.77096665, -0.70466797, -1.26871486, -0.87865403, -0.11398154,
        0.28291267, -0.44780411, -1.29022737, -0.63258649,  2.38109657])

In [22]:
np.random.randn(5,5)
#El tamaño de la muestra puede ser un número entero (para un arreglo unidimensional) o dos enteros separados por comas (para un arreglo bidimensional).

array([[ 0.501914  ,  0.35535519, -0.50201412,  1.46809486,  1.05376382],
       [ 0.39060689,  1.02755445,  0.42959371,  0.03096559, -0.50839987],
       [ 0.81031816,  0.55550717,  0.38810665, -0.61271674, -1.64066097],
       [ 0.71971433,  0.78014072, -1.13262868, -1.56653587, -2.3084084 ],
       [-0.64352676,  0.14216008, -1.31851232, -1.00603768,  0.85504295]])

In [29]:
np.random.randint(1, 10,20)
#Devuelve una muestra de números enteros que son mayores o iguales que el primer parámetro y menores que el segundo 

array([4, 6, 3, 3, 6, 6, 2, 8, 8, 8, 4, 6, 1, 9, 3, 9, 5, 2, 7, 1])

## Reestructuración de datos con Numpy y funciones incorporadas
Podemos reestructurar los arrays y transformarlos en matrices y viceversa. Por ejemplo, para transformar un array de seis elementos en un matriz de 2x3:

In [30]:
arr = np.array([0,1,2,3,4,5])

arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

Aprendamos cuatro métodos útiles para identificar los valores máximo y mínimo dentro de un array NumPy:

In [32]:
simple_array =  np.array([1, 2, 3, 4])

simple_array.max()

4

La función argmax, en lugar del valor máximo, nos proporciona el índice en el que se encuentra a su vez el valor máximo:

In [34]:
simple_array.argmax()

3

In [35]:
print(simple_array.min())

print(simple_array.argmin())

1
0


## Operaciones con NumPy

Al sumar un sólo número a un arreglo de NumPy, ese número se suma a cada elemento en el arreglo. A continuación se ve un ejemplo:

In [37]:
print(arr)
print(2 + arr)

#Devuelve array([2, 3, 4, 5])

[0 1 2 3 4 5]
[2 3 4 5 6 7]


Puedes sumar dos arrays NumPy usando el operador +. Los arrays se suman elemento por elemento (lo que significa que los primeros elementos se suman entre si, los segundos elementos se suman se suman entre se, y así sucesivamente).

In [38]:
arr + arr

array([ 0,  2,  4,  6,  8, 10])

De manera similar podemos usuar los operadores -, * y /.

También podemos usar operadores relacionales, por ejemplo:

In [39]:
arr>3

array([False, False, False, False,  True,  True])